basePath: /api
definitions:
  Message:
    properties:
      message:
        type: string
    type: object
host: localhost:8888
info:
  contact: {}
  description: This is a sample server celler server.
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/ping:
    get:
      description: AUTH Ping-Pong
      operationId: auth-ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Message'
      security:
      - BasicAuth: []
      summary: AUTH Ping-Pong-Title
      tags:
      - Ping
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
